/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsForm: typeof import('./src/components/SettingsForm.vue')['default']
    SettingsSkeleton: typeof import('./src/components/SettingsSkeleton.vue')['default']
    SettingsView: typeof import('./src/views/SettingsView.vue')['default']
    ThemeCard: typeof import('./src/components/ThemeCard.vue')['default']
    ThemeGrid: typeof import('./src/components/ThemeGrid.vue')['default']
    ThemeSkeleton: typeof import('./src/components/ThemeSkeleton.vue')['default']
    ThemesView: typeof import('./src/views/ThemesView.vue')['default']
  }
}
