name: Crowdin Sync
on:
  schedule:
    - cron: "0 0 2/2 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: nightly
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: pnpm install
      - name: Sync with Crowdin
        run: pnpm crowdin:upload && pnpm crowdin:download
      - uses: actions/push@v3
        with:
          ref: nightly
          token: ${{ secrets.GITHUB_TOKEN }}
