name: "Test"

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            target: "x86_64-pc-windows-msvc"
          - platform: "windows-latest"
            target: "aarch64-pc-windows-msvc"
          - platform: "ubuntu-latest"
            target: "x86_64-unknown-linux-gnu"
          - platform: "ubuntu-latest"
            target: "aarch64-unknown-linux-gnu"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: setup volta
        uses: volta-cli/action@v4.2.1
        with:
          node-version: 24

      - name: install pnpm
        run: volta install pnpm

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install target
        run: rustup target add ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: install frontend dependencies
        run: pnpm install

      - uses: actions-js/push@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: build app
        run: pnpm tauri:build --target ${{ matrix.target }}

      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: smtc2web-${{ matrix.target }}-${{ github.sha }}
          path: src-tauri/target/${{ matrix.target }}/release/bundle
          fail-on-missing: true
